# Generated by Django 5.0.7 on 2024-07-19 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='credential',
            name='siigo_app',
        ),
    ]
