# Generated by Django 5.0.7 on 2024-07-16 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(default='0000000000', max_length=255, unique=True, verbose_name='Documento de Identidad'),
        ),
    ]
